# **DECISION TREE CLASSIFIER**

In [ ]:
# DECISION TREE CLASSIFIER

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/BDA/Parkinsons_big data.csv')
df

,name,MDVP:Fo(Hz),MDVP:Fhi(Hz),MDVP:Flo(Hz),MDVP:Jitter(%),MDVP:Jitter(Abs),MDVP:RAP,MDVP:PPQ,Jitter:DDP,MDVP:Shimmer,...,Shimmer:DDA,NHR,HNR,status,RPDE,DFA,spread1,spread2,D2,PPE
0,phon_R01_S27_3,138.190,203.522,83.340,0.00460,0.000030,0.00226,0.00207,0.00677,0.02184,...,0.03724,0.00420,25.690,1,0.450798,0.741480,-6.051233,0.273280,2.640798,0.170106
1,phon_R01_S05_3,96.106,108.664,84.510,0.00606,0.000060,0.00351,0.00348,0.01063,0.03070,...,0.05000,0.01225,17.536,1,0.653139,0.770466,-5.187987,0.259229,2.151121,0.265311
2,phon_R01_S49_5,128.940,479.697,88.251,0.00500,0.000020,0.00270,0.00284,0.00810,0.03999,...,0.07238,0.00905,22.370,0,0.603515,0.684130,-5.619070,0.191576,2.027228,0.215724
3,phon_R01_S31_4,91.904,115.871,86.292,0.00608,0.000060,0.00331,0.00332,0.00994,0.02362,...,0.03706,0.01810,18.857,1,0.408598,0.792520,-5.517173,0.216204,2.679185,0.220657
4,phon_R01_S24_5,183.520,216.814,161.340,0.01872,0.000100,0.01075,0.01154,0.03225,0.06170,...,0.09669,0.10952,15.060,1,0.611679,0.768974,-4.484303,0.230532,2.958815,0.301487
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,phon_R01_S06_3,116.676,137.871,111.366,0.00459,0.000030,0.00250,0.00256,0.00750,0.01966,...,0.02666,0.01095,25.908,1,0.450798,0.819235,-6.051233,0.273280,2.640798,0.160306
99996,phon_R01_S07_3,180.198,201.249,175.456,0.00204,0.000009,0.00113,0.00113,0.00339,0.01263,...,0.01919,0.00119,30.775,0,0.522812,0.766209,-7.304500,0.171088,2.095237,0.086398
99997,phon_R01_S31_1,180.978,200.125,155.495,0.00968,0.000080,0.00463,0.00750,0.01388,0.05701,...,0.07253,0.01222,18.305,1,0.458359,0.727747,-4.075192,0.335590,2.486855,0.368674
99998,phon_R01_S08_4,180.978,200.125,155.495,0.00331,0.000030,0.00168,0.00171,0.00504,0.01663,...,0.02488,0.00265,26.310,1,0.458556,0.727747,-6.257440,0.139610,2.286875,0.140608
99999,phon_R01_S32_6,122.964,130.049,114.676,0.00440,0.000030,0.00214,0.00181,0.00641,0.01033,...,0.01614,0.01724,26.842,1,0.462516,0.754073,-5.517173,0.389295,2.925862,0.220617

In [ ]:
df.isnull().sum()

name                0
MDVP:Fo(Hz)         0
MDVP:Fhi(Hz)        0
MDVP:Flo(Hz)        2
MDVP:Jitter(%)      0
MDVP:Jitter(Abs)    1
MDVP:RAP            0
MDVP:PPQ            0
Jitter:DDP          0
MDVP:Shimmer        0
MDVP:Shimmer(dB)    0
Shimmer:APQ3        0
Shimmer:APQ5        0
MDVP:APQ            1
Shimmer:DDA         0
NHR                 0
HNR                 0
status              0
RPDE                0
DFA                 0
spread1             0
spread2             0
D2                  1
PPE                 0
dtype: int64

In [ ]:
df['MDVP:Flo(Hz)']=df['MDVP:Flo(Hz)'].fillna(df['MDVP:Flo(Hz)'].mean())

In [ ]:
df['MDVP:Jitter(Abs)']=df['MDVP:Jitter(Abs)'].fillna(df['MDVP:Jitter(Abs)'].mean())

In [ ]:
df['MDVP:APQ']=df['MDVP:APQ'].fillna(df['MDVP:APQ'].mean())

In [ ]:
df['D2']=df['D2'].fillna(df['D2'].mean())

In [ ]:
df.isnull().sum()

name                0
MDVP:Fo(Hz)         0
MDVP:Fhi(Hz)        0
MDVP:Flo(Hz)        0
MDVP:Jitter(%)      0
MDVP:Jitter(Abs)    0
MDVP:RAP            0
MDVP:PPQ            0
Jitter:DDP          0
MDVP:Shimmer        0
MDVP:Shimmer(dB)    0
Shimmer:APQ3        0
Shimmer:APQ5        0
MDVP:APQ            0
Shimmer:DDA         0
NHR                 0
HNR                 0
status              0
RPDE                0
DFA                 0
spread1             0
spread2             0
D2                  0
PPE                 0
dtype: int64

In [ ]:
features=df.loc[:,df.columns!='status'].values[:,1:]
labels=df.loc[:,'status'].values

In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler((-1,1))
X = scaler.fit_transform(features)
y = labels

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state = 7)

In [ ]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier(criterion='entropy',max_depth=10,random_state=7)
dt.fit(X_train,y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=10, random_state=7)

In [ ]:
y_pred = dt.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_pred,y_test)*100)

93.77

# **DECISION TREE REGRESSOR**

In [ ]:
# DECISION TREE REGRESSOR

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/ML/Boston.csv')
df

,Unnamed: 0,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
0,1,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,2,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,3,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,4,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,5,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,502,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67,22.4
502,503,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,504,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,505,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0
505,506,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88,11.9

In [ ]:
df.isnull().sum()

Unnamed: 0    0
crim          0
zn            0
indus         0
chas          0
nox           0
rm            0
age           0
dis           0
rad           0
tax           0
ptratio       0
black         0
lstat         0
medv          0
dtype: int64

In [ ]:
df.duplicated().sum()

0

In [ ]:
df.corr()

,Unnamed: 0,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
Unnamed: 0,1.000000,0.407407,-0.103393,0.399439,-0.003759,0.398736,-0.079971,0.203784,-0.302211,0.686002,0.666626,0.291074,-0.295041,0.258465,-0.226604
crim,0.407407,1.000000,-0.200469,0.406583,-0.055892,0.420972,-0.219247,0.352734,-0.379670,0.625505,0.582764,0.289946,-0.385064,0.455621,-0.388305
zn,-0.103393,-0.200469,1.000000,-0.533828,-0.042697,-0.516604,0.311991,-0.569537,0.664408,-0.311948,-0.314563,-0.391679,0.175520,-0.412995,0.360445
indus,0.399439,0.406583,-0.533828,1.000000,0.062938,0.763651,-0.391676,0.644779,-0.708027,0.595129,0.720760,0.383248,-0.356977,0.603800,-0.483725
chas,-0.003759,-0.055892,-0.042697,0.062938,1.000000,0.091203,0.091251,0.086518,-0.099176,-0.007368,-0.035587,-0.121515,0.048788,-0.053929,0.175260
nox,0.398736,0.420972,-0.516604,0.763651,0.091203,1.000000,-0.302188,0.731470,-0.769230,0.611441,0.668023,0.188933,-0.380051,0.590879,-0.427321
rm,-0.079971,-0.219247,0.311991,-0.391676,0.091251,-0.302188,1.000000,-0.240265,0.205246,-0.209847,-0.292048,-0.355501,0.128069,-0.613808,0.695360
age,0.203784,0.352734,-0.569537,0.644779,0.086518,0.731470,-0.240265,1.000000,-0.747881,0.456022,0.506456,0.261515,-0.273534,0.602339,-0.376955
dis,-0.302211,-0.379670,0.664408,-0.708027,-0.099176,-0.769230,0.205246,-0.747881,1.000000,-0.494588,-0.534432,-0.232471,0.291512,-0.496996,0.249929
rad,0.686002,0.625505,-0.311948,0.595129,-0.007368,0.611441,-0.209847,0.456022,-0.494588,1.000000,0.910228,0.464741,-0.444413,0.488676,-0.381626
tax,0.666626,0.582764,-0.314563,0.720760,-0.035587,0.668023,-0.292048,0.506456,-0.534432,0.910228,1.000000,0.460853,-0.441808,0.543993,-0.468536
ptratio,0.291074,0.289946,-0.391679,0.383248,-0.121515,0.188933,-0.355501,0.261515,-0.232471,0.464741,0.460853,1.000000,-0.177383,0.374044,-0.507787
black,-0.295041,-0.385064,0.175520,-0.356977,0.048788,-0.380051,0.128069,-0.273534,0.291512,-0.444413,-0.441808,-0.177383,1.000000,-0.366087,0.333461
lstat,0.258465,0.455621,-0.412995,0.603800,-0.053929,0.590879,-0.613808,0.602339,-0.496996,0.488676,0.543993,0.374044,-0.366087,1.000000,-0.737663
medv,-0.226604,-0.388305,0.360445,-0.483725,0.175260,-0.427321,0.695360,-0.376955,0.249929,-0.381626,-0.468536,-0.507787,0.333461,-0.737663,1.000000

In [ ]:
X = df.drop(['medv'],axis=1).values
y = df['medv'].values

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state = 7)

In [ ]:
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()
X_train=ss.fit_transform(X_train)
X_test=ss.transform(X_test)

In [ ]:
from sklearn.tree import DecisionTreeRegressor
dtr = DecisionTreeRegressor(criterion = 'squared_error',max_depth=10,random_state=7)
dtr.fit(X_train,y_train)

DecisionTreeRegressor(max_depth=10, random_state=7)

In [ ]:
y_pred = dtr.predict(X_test)

In [ ]:
from sklearn.metrics import r2_score as score
print(score(y_pred,y_test)*100)

69.09971201928803

In [ ]:
from sklearn.metrics import mean_squared_error as mse
mse(y_pred,y_test)

29.264037850060124

In [ ]:
# X_train = X_train.reshape(-1,1)
# y_train = y_train.reshape(-1,1)
# X_test = X_test.reshape(-1,1)